### ISSUE TITLE
Closes automatically and missing exes

### ISSUE THREAD

**Issue by anic17** [Illegal-Services/Discord-Cache-Viewer#2]
I tried this script on my laptop, and I can see from the source code that some external exes like `grep` or `curl` are missing.
And, when I run it, it closes instantly. It also finishes the cmd process, so even running it from cmd ends the process.

Use `exit /b` to avoid that behavior.

**Comment by BUZZARDGTA** [comment]
Hi, thanks for your feedback.
Missing executable files from GitHub source fixed.

I still am thinking if I should remove `exit 0` to `exit /b 0`.

**Comment by BUZZARDGTA** [comment]
> "when I run it, it closes instantly"

Sadly I cannot fix that issue without more debugging from you because I've never experienced such problem.

**Comment by BUZZARDGTA** [comment]
Update: I found out that when the code crash is when some dependencies are missing.
The setup part fails because I have removed the vbscript source code by mistake.
I will be fixing that bug soon, in a few hours.

**Comment by BUZZARDGTA** [comment]
Problem fixed, gonna be soon updating source code:

![cmd_2022-01-19_13-10](https://user-images.githubusercontent.com/62464560/150126896-ebfeb372-0be6-4af9-8251-614aed7e83cd.png)

**Comment by BUZZARDGTA** [comment]
Also after thinking and reflexion, I've decided to remove `exit 0` for `exit /b 0`, just has you asked me to do.

Since it wont impact the normal users at all, but help debugging, I believe there's no boring side effect to use it.

**Comment by anic17** [comment]
> Also after thinking and reflexion, I've decided to remove `exit 0` for `exit /b 0`, just has you asked me to do.
> 
> Since it wont impact the normal users at all, but help debugging, I believe there's no boring side effect to use it.

That's the reason I prefer `exit /b`

**Comment by BUZZARDGTA** [comment]
Fixed all issues rported in this thread: https://github.com/Illegal-Services/Discord-Cache-Viewer/commit/fdd8088149fd7ff4beb7222f0fd29de2f26f407a
